---
- name: Simple CSV Reader
  hosts: 192.168.134.129
  gather_facts: false

  vars:
    csv_path: /opt/GCP/Subnet.csv

  tasks:

    - name: Read CSV file content from remote server
      slurp:
        src: "{{ csv_path }}"
      register: csv_raw

    - name: Decode CSV text
      set_fact:
        csv_text: "{{ csv_raw.content | b64decode }}"

    - name: Show CSV output
      debug:
        msg: "{{ csv_text }}"
